/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import model.bean.ConfigBEAN;
import util.ConfigFileFactory;

/**
 *
 * @author Eduardo F Silva a.k.a Eduardu44
 */
public class FirstStartConfig extends javax.swing.JFrame {

    private Color BG = new Color(240, 240, 240);
    private Color FG = new Color(0, 0, 0);
    private static final String NUM_FIELD_FILTER = "0987654321";
    private boolean flags[] = new boolean[]{false};
    private ConfigFileFactory cff = new ConfigFileFactory();

    /**
     * Creates new form FirstStartConfig
     */
    public FirstStartConfig() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grbtnDB = new javax.swing.ButtonGroup();
        seletorCor = new javax.swing.JColorChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        rbtnSqlite = new javax.swing.JRadioButton();
        rbtnMysql = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        tfDBPass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfDBPort = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfDBUser = new javax.swing.JTextField();
        tfDBHost = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnAltBG = new javax.swing.JButton();
        btnAltFG = new javax.swing.JButton();
        btnAltRealce = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pnCorFG = new javax.swing.JPanel();
        pnCorBG = new javax.swing.JPanel();
        pnCorRealce = new javax.swing.JPanel();
        pnCorTextBG = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnAltTextBG = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        tfG = new javax.swing.JTextField();
        tfB = new javax.swing.JTextField();
        tfR = new javax.swing.JTextField();
        btnRestaurarPaleta = new javax.swing.JButton();
        chbManualInput = new javax.swing.JCheckBox();
        pnCorPreview = new javax.swing.JPanel();
        btnSaveQuit = new javax.swing.JButton();
        btnSaveLoad = new javax.swing.JButton();
        btnQuitOnly = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        chbDarkMode = new javax.swing.JCheckBox();
        chbSaveLogin = new javax.swing.JCheckBox();
        chbAutoLogin = new javax.swing.JCheckBox();
        chbDownloadIndex = new javax.swing.JCheckBox();
        chbBypassDialog = new javax.swing.JCheckBox();
        chbSysTray = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ESYS - Configuração Inicial");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Configurações De Persistência");

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));

        rbtnSqlite.setBackground(new java.awt.Color(0, 0, 0));
        grbtnDB.add(rbtnSqlite);
        rbtnSqlite.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        rbtnSqlite.setForeground(new java.awt.Color(255, 255, 255));
        rbtnSqlite.setText("DB Portatil (SQLite)");
        rbtnSqlite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSqliteActionPerformed(evt);
            }
        });

        rbtnMysql.setBackground(new java.awt.Color(0, 0, 0));
        grbtnDB.add(rbtnMysql);
        rbtnMysql.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        rbtnMysql.setForeground(new java.awt.Color(255, 255, 255));
        rbtnMysql.setSelected(true);
        rbtnMysql.setText("DB Fixa (MySQL)");
        rbtnMysql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMysqlActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tipo De Banco");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtnSqlite)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtnMysql, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(147, 147, 147))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnMysql)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnSqlite)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tfDBPass.setBackground(new java.awt.Color(51, 51, 51));
        tfDBPass.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        tfDBPass.setForeground(new java.awt.Color(255, 255, 255));
        tfDBPass.setText("root");

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Senha");

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Host");

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario");

        tfDBPort.setBackground(new java.awt.Color(51, 51, 51));
        tfDBPort.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        tfDBPort.setForeground(new java.awt.Color(255, 255, 255));
        tfDBPort.setText("3307");

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Configuração MySQL");

        tfDBUser.setBackground(new java.awt.Color(51, 51, 51));
        tfDBUser.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        tfDBUser.setForeground(new java.awt.Color(255, 255, 255));
        tfDBUser.setText("root");

        tfDBHost.setBackground(new java.awt.Color(51, 51, 51));
        tfDBHost.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        tfDBHost.setForeground(new java.awt.Color(255, 255, 255));
        tfDBHost.setText("127.0.0.1");

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Porta");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfDBHost, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfDBUser, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfDBPort, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfDBPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDBUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDBPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDBHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDBPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cores");

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));

        btnAltBG.setBackground(new java.awt.Color(0, 0, 0));
        btnAltBG.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        btnAltBG.setForeground(new java.awt.Color(255, 255, 255));
        btnAltBG.setText("Alterar");
        btnAltBG.setToolTipText("");
        btnAltBG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltBGActionPerformed(evt);
            }
        });

        btnAltFG.setBackground(new java.awt.Color(0, 0, 0));
        btnAltFG.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        btnAltFG.setForeground(new java.awt.Color(255, 255, 255));
        btnAltFG.setText("Alterar");
        btnAltFG.setToolTipText("");
        btnAltFG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltFGActionPerformed(evt);
            }
        });

        btnAltRealce.setBackground(new java.awt.Color(0, 0, 0));
        btnAltRealce.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        btnAltRealce.setForeground(new java.awt.Color(255, 255, 255));
        btnAltRealce.setText("Alterar");
        btnAltRealce.setToolTipText("");
        btnAltRealce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltRealceActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Background");

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Foreground");

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Realce");

        pnCorFG.setBackground(new java.awt.Color(255, 255, 255));
        pnCorFG.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));

        javax.swing.GroupLayout pnCorFGLayout = new javax.swing.GroupLayout(pnCorFG);
        pnCorFG.setLayout(pnCorFGLayout);
        pnCorFGLayout.setHorizontalGroup(
            pnCorFGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        pnCorFGLayout.setVerticalGroup(
            pnCorFGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        pnCorBG.setBackground(new java.awt.Color(0, 0, 0));
        pnCorBG.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        pnCorBG.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout pnCorBGLayout = new javax.swing.GroupLayout(pnCorBG);
        pnCorBG.setLayout(pnCorBGLayout);
        pnCorBGLayout.setHorizontalGroup(
            pnCorBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        pnCorBGLayout.setVerticalGroup(
            pnCorBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        pnCorRealce.setBackground(new java.awt.Color(0, 0, 102));
        pnCorRealce.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));

        javax.swing.GroupLayout pnCorRealceLayout = new javax.swing.GroupLayout(pnCorRealce);
        pnCorRealce.setLayout(pnCorRealceLayout);
        pnCorRealceLayout.setHorizontalGroup(
            pnCorRealceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        pnCorRealceLayout.setVerticalGroup(
            pnCorRealceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        pnCorTextBG.setBackground(new java.awt.Color(51, 51, 51));
        pnCorTextBG.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));

        javax.swing.GroupLayout pnCorTextBGLayout = new javax.swing.GroupLayout(pnCorTextBG);
        pnCorTextBG.setLayout(pnCorTextBGLayout);
        pnCorTextBGLayout.setHorizontalGroup(
            pnCorTextBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        pnCorTextBGLayout.setVerticalGroup(
            pnCorTextBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Text BG");

        btnAltTextBG.setBackground(new java.awt.Color(0, 0, 0));
        btnAltTextBG.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        btnAltTextBG.setForeground(new java.awt.Color(255, 255, 255));
        btnAltTextBG.setText("Alterar");
        btnAltTextBG.setToolTipText("");
        btnAltTextBG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltTextBGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnCorBG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnCorFG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(btnAltBG))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(btnAltFG)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(pnCorRealce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(pnCorTextBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12)))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAltTextBG)
                    .addComponent(btnAltRealce))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(pnCorFG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAltRealce)
                                .addComponent(jLabel10))
                            .addComponent(pnCorRealce, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAltBG)
                                .addComponent(jLabel8)
                                .addComponent(pnCorBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pnCorTextBG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAltTextBG)
                                    .addComponent(jLabel12)))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAltFG)
                                .addComponent(jLabel9)))
                        .addGap(39, 39, 39))))
        );

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));

        tfG.setBackground(new java.awt.Color(51, 51, 51));
        tfG.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        tfG.setForeground(new java.awt.Color(255, 255, 255));
        tfG.setText("0");
        tfG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfGKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfGKeyTyped(evt);
            }
        });

        tfB.setBackground(new java.awt.Color(51, 51, 51));
        tfB.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        tfB.setForeground(new java.awt.Color(255, 255, 255));
        tfB.setText("0");
        tfB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfBKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfBKeyTyped(evt);
            }
        });

        tfR.setBackground(new java.awt.Color(51, 51, 51));
        tfR.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        tfR.setForeground(new java.awt.Color(255, 255, 255));
        tfR.setText("0");
        tfR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfRKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfRKeyTyped(evt);
            }
        });

        btnRestaurarPaleta.setBackground(new java.awt.Color(51, 51, 51));
        btnRestaurarPaleta.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        btnRestaurarPaleta.setForeground(new java.awt.Color(255, 255, 255));
        btnRestaurarPaleta.setText("Restaurar Paleta Padrão");
        btnRestaurarPaleta.setToolTipText("");
        btnRestaurarPaleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarPaletaActionPerformed(evt);
            }
        });

        chbManualInput.setBackground(new java.awt.Color(0, 0, 0));
        chbManualInput.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        chbManualInput.setForeground(new java.awt.Color(255, 255, 255));
        chbManualInput.setText("Manual Input");
        chbManualInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbManualInputActionPerformed(evt);
            }
        });

        pnCorPreview.setBackground(new java.awt.Color(0, 0, 0));
        pnCorPreview.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        pnCorPreview.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout pnCorPreviewLayout = new javax.swing.GroupLayout(pnCorPreview);
        pnCorPreview.setLayout(pnCorPreviewLayout);
        pnCorPreviewLayout.setHorizontalGroup(
            pnCorPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        pnCorPreviewLayout.setVerticalGroup(
            pnCorPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbManualInput)
                .addGap(18, 18, 18)
                .addComponent(pnCorPreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRestaurarPaleta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnCorPreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRestaurarPaleta)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chbManualInput)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tfB.getAccessibleContext().setAccessibleName("");

        btnSaveQuit.setBackground(new java.awt.Color(0, 0, 0));
        btnSaveQuit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        btnSaveQuit.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveQuit.setText("Salvar E Fechar");
        btnSaveQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveQuitActionPerformed(evt);
            }
        });

        btnSaveLoad.setBackground(new java.awt.Color(0, 0, 0));
        btnSaveLoad.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        btnSaveLoad.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveLoad.setText("Salvar E Carregar");
        btnSaveLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveLoadActionPerformed(evt);
            }
        });

        btnQuitOnly.setBackground(new java.awt.Color(0, 0, 0));
        btnQuitOnly.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        btnQuitOnly.setForeground(new java.awt.Color(255, 255, 255));
        btnQuitOnly.setText("Fechar Sem Salvar");
        btnQuitOnly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitOnlyActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));

        chbDarkMode.setBackground(new java.awt.Color(0, 0, 0));
        chbDarkMode.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        chbDarkMode.setForeground(new java.awt.Color(255, 255, 255));
        chbDarkMode.setSelected(true);
        chbDarkMode.setText("Dark Mode");

        chbSaveLogin.setBackground(new java.awt.Color(0, 0, 0));
        chbSaveLogin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        chbSaveLogin.setForeground(new java.awt.Color(255, 255, 255));
        chbSaveLogin.setText("Salvar Ultimo Login");
        chbSaveLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbSaveLoginActionPerformed(evt);
            }
        });

        chbAutoLogin.setBackground(new java.awt.Color(0, 0, 0));
        chbAutoLogin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        chbAutoLogin.setForeground(new java.awt.Color(255, 255, 255));
        chbAutoLogin.setText("Login Automático");
        chbAutoLogin.setToolTipText("Salvar Último Login Precisa Estar Marcado");
        chbAutoLogin.setEnabled(false);

        chbDownloadIndex.setBackground(new java.awt.Color(0, 0, 0));
        chbDownloadIndex.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        chbDownloadIndex.setForeground(new java.awt.Color(255, 255, 255));
        chbDownloadIndex.setSelected(true);
        chbDownloadIndex.setText("Baixar Indices Ao Iniciar");

        chbBypassDialog.setBackground(new java.awt.Color(0, 0, 0));
        chbBypassDialog.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        chbBypassDialog.setForeground(new java.awt.Color(255, 255, 255));
        chbBypassDialog.setText("Ignorar Dialog Box");

        chbSysTray.setBackground(new java.awt.Color(0, 0, 0));
        chbSysTray.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        chbSysTray.setForeground(new java.awt.Color(255, 255, 255));
        chbSysTray.setSelected(true);
        chbSysTray.setText("Usar Icone De Bandeja");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbSysTray)
                    .addComponent(chbBypassDialog)
                    .addComponent(chbDownloadIndex)
                    .addComponent(chbAutoLogin)
                    .addComponent(chbSaveLogin)
                    .addComponent(chbDarkMode))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chbDarkMode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbSaveLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbAutoLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbDownloadIndex)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbBypassDialog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbSysTray)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Outras Configurações");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(btnSaveLoad)
                .addGap(18, 18, 18)
                .addComponent(btnSaveQuit)
                .addGap(18, 18, 18)
                .addComponent(btnQuitOnly)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel13))
                        .addGap(13, 13, 13)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveLoad)
                    .addComponent(btnSaveQuit)
                    .addComponent(btnQuitOnly))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnMysqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMysqlActionPerformed
        tfDBHost.setEnabled(true);
        tfDBPort.setEnabled(true);
        tfDBPass.setEnabled(true);
        tfDBUser.setEnabled(true);
    }//GEN-LAST:event_rbtnMysqlActionPerformed

    private void rbtnSqliteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSqliteActionPerformed
        tfDBHost.setEnabled(false);
        tfDBPort.setEnabled(false);
        tfDBPass.setEnabled(false);
        tfDBUser.setEnabled(false);
    }//GEN-LAST:event_rbtnSqliteActionPerformed

    private void tfRKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfRKeyReleased
        if (!tfR.getText().trim().equals("")) {
            int val = Integer.valueOf(tfR.getText());
            if (val > 255) {
                tfR.setText("255");
            }
        }
        setPreview();
    }//GEN-LAST:event_tfRKeyReleased

    private void tfBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBKeyReleased
        if (!tfB.getText().trim().equals("")) {
            int val = Integer.valueOf(tfB.getText());
            if (val > 255) {
                tfB.setText("255");
            }
        }
        setPreview();
    }//GEN-LAST:event_tfBKeyReleased
    private void tfGKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfGKeyReleased
        if (!tfG.getText().trim().equals("")) {
            int val = Integer.valueOf(tfG.getText());
            if (val > 255) {
                tfG.setText("255");
            }
        }
        setPreview();
    }//GEN-LAST:event_tfGKeyReleased

    private void tfRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfRKeyTyped
        if (!NUM_FIELD_FILTER.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfRKeyTyped

    private void tfGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfGKeyTyped
        if (!NUM_FIELD_FILTER.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfGKeyTyped

    private void tfBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBKeyTyped
        if (!NUM_FIELD_FILTER.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfBKeyTyped

    private void btnAltBGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltBGActionPerformed
        Color ret = obterCor(pnCorBG.getBackground());
        pnCorBG.setBackground(ret);
    }//GEN-LAST:event_btnAltBGActionPerformed

    private void btnAltFGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltFGActionPerformed
        Color ret = obterCor(pnCorFG.getBackground());
        pnCorFG.setBackground(ret);
    }//GEN-LAST:event_btnAltFGActionPerformed

    private void btnAltRealceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltRealceActionPerformed
        Color ret = obterCor(pnCorRealce.getBackground());
        pnCorRealce.setBackground(ret);
    }//GEN-LAST:event_btnAltRealceActionPerformed

    private void btnRestaurarPaletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarPaletaActionPerformed
        pnCorBG.setBackground(new Color(0, 0, 0));
        pnCorFG.setBackground(new Color(255, 255, 255));
        pnCorRealce.setBackground(new Color(0, 0, 102));
       pnCorTextBG.setBackground(new Color(51, 51, 51));
        tfR.setText("0");
        tfG.setText("0");
        tfB.setText("0");
        setPreview();
        chbManualInput.setSelected(false);
    }//GEN-LAST:event_btnRestaurarPaletaActionPerformed

    private void btnAltTextBGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltTextBGActionPerformed
        Color ret = obterCor(pnCorTextBG.getBackground());
        pnCorTextBG.setBackground(ret);
    }//GEN-LAST:event_btnAltTextBGActionPerformed

    private void chbManualInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbManualInputActionPerformed
        if (chbManualInput.isSelected()) {
            if (!flags[0]) {
                JOptionPane.showMessageDialog(this, "Aperte O Botão \"Alterar\" Para Carregar A Cor Na Opção");
                flags[0] = true;
            }
        }
    }//GEN-LAST:event_chbManualInputActionPerformed

    private void btnSaveQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveQuitActionPerformed
        cff.writeFile(carregarBean());
        System.exit(0);
    }//GEN-LAST:event_btnSaveQuitActionPerformed

    private void btnSaveLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveLoadActionPerformed
        cff.writeFile(carregarBean());
        try {
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
        } catch (Exception ex) {
        }
        setVisible(false);
        System.out.println("[ESYS-INFO] Carregando Splash Em Modo Metal");
        new SplashScreen().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSaveLoadActionPerformed

    private void btnQuitOnlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitOnlyActionPerformed
        if (chbBypassDialog.isSelected()) {
            System.exit(0);
        } else {
            int opc = JOptionPane.showConfirmDialog(this, "Deseja Salvar Antes De Sair ?", "Salvar", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            switch (opc) {
                case JOptionPane.YES_OPTION:
                    cff.writeFile(carregarBean());
                    System.exit(0);
                    break;
                case JOptionPane.NO_OPTION:
                    System.exit(0);
                    break;
            }
        }
    }//GEN-LAST:event_btnQuitOnlyActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (chbBypassDialog.isSelected()) {
            System.exit(0);
        } else {
            int opc = JOptionPane.showConfirmDialog(this, "Deseja Salvar Antes De Sair ?", "Salvar", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            switch (opc) {
                case JOptionPane.YES_OPTION:
                    cff.writeFile(carregarBean());
                    System.exit(0);
                    break;
                case JOptionPane.NO_OPTION:
                    System.exit(0);
                    break;
            }
        }
    }//GEN-LAST:event_formWindowClosing

    private void chbSaveLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbSaveLoginActionPerformed
        if (chbSaveLogin.isSelected()) {
            chbAutoLogin.setEnabled(true);
            chbAutoLogin.setToolTipText("");
            chbAutoLogin.setSelected(true);
        } else {
            chbAutoLogin.setEnabled(false);
            chbAutoLogin.setToolTipText(null);
            chbAutoLogin.setSelected(false);
        }
    }//GEN-LAST:event_chbSaveLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstStartConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstStartConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstStartConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstStartConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstStartConfig().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltBG;
    private javax.swing.JButton btnAltFG;
    private javax.swing.JButton btnAltRealce;
    private javax.swing.JButton btnAltTextBG;
    private javax.swing.JButton btnQuitOnly;
    private javax.swing.JButton btnRestaurarPaleta;
    private javax.swing.JButton btnSaveLoad;
    private javax.swing.JButton btnSaveQuit;
    private javax.swing.JCheckBox chbAutoLogin;
    private javax.swing.JCheckBox chbBypassDialog;
    private javax.swing.JCheckBox chbDarkMode;
    private javax.swing.JCheckBox chbDownloadIndex;
    private javax.swing.JCheckBox chbManualInput;
    private javax.swing.JCheckBox chbSaveLogin;
    private javax.swing.JCheckBox chbSysTray;
    private javax.swing.ButtonGroup grbtnDB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel pnCorBG;
    private javax.swing.JPanel pnCorFG;
    private javax.swing.JPanel pnCorPreview;
    private javax.swing.JPanel pnCorRealce;
    private javax.swing.JPanel pnCorTextBG;
    private javax.swing.JRadioButton rbtnMysql;
    private javax.swing.JRadioButton rbtnSqlite;
    private javax.swing.JColorChooser seletorCor;
    private javax.swing.JTextField tfB;
    private javax.swing.JTextField tfDBHost;
    private javax.swing.JPasswordField tfDBPass;
    private javax.swing.JTextField tfDBPort;
    private javax.swing.JTextField tfDBUser;
    private javax.swing.JTextField tfG;
    private javax.swing.JTextField tfR;
    // End of variables declaration//GEN-END:variables

    private Color obterCor(Color corInicial) {
        Color c = corInicial;
        if (chbManualInput.isSelected()) {
            Color manual = new Color(Integer.valueOf(tfR.getText()), Integer.valueOf(tfG.getText()), Integer.valueOf(tfB.getText()));
            c = manual;
            chbManualInput.setSelected(false);
        } else {
            Color picker = seletorCor.showDialog(null, "Escolha Uma Cor", corInicial);
            tfR.setText(picker.getRed() + "");
            tfG.setText(picker.getGreen() + "");
            tfB.setText(picker.getBlue() + "");
            c = picker;
            setPreview();
        }
        return c;
    }

    private void setPreview() {
        int r = ((tfR.getText().trim().equals("")) ? 0 : Integer.valueOf(tfR.getText()));
        int g = ((tfG.getText().trim().equals("")) ? 0 : Integer.valueOf(tfG.getText()));
        int b = ((tfB.getText().trim().equals("")) ? 0 : Integer.valueOf(tfB.getText()));
        Color c = new Color(r, g, b);
        pnCorPreview.setBackground(c);
    }

    private ConfigBEAN carregarBean() {
        ConfigBEAN cb = new ConfigBEAN();
        cb.initObject();
        cb.setColors(new Color[]{getBG(pnCorBG), getBG(pnCorFG), getBG(pnCorRealce), getBG(pnCorTextBG)});
        cb.setOptions(readOptions());
        if (rbtnMysql.isSelected()) {
            cb.setDatabaseDriver("com.mysql.jdbc.Driver");
            cb.setDatabaseType("mysql");
            cb.setDbData(new String[]{tfDBUser.getText(), new String(tfDBPass.getPassword()), tfDBHost.getText(), tfDBPort.getText()});
        } else if (rbtnMysql.isSelected()) {
            cb.setDatabaseDriver("org.sqlite.JDBC");
            cb.setDatabaseType("sqlite");
            cb.setDbData(new String[]{"", "", "", ""});
        }
        return cb;
    }

    private Color getBG(JPanel pn) {
        return pn.getBackground();
    }

    private boolean[] readOptions() {
        boolean b[] = new boolean[6];
        b[0] = chbDarkMode.isSelected();
        b[1] = chbSaveLogin.isSelected();
        b[2] = chbAutoLogin.isSelected();
        b[3] = chbDownloadIndex.isSelected();
        b[4] = chbBypassDialog.isSelected();
        b[5] = chbSysTray.isSelected();
        return b;
    }
}
