/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.UserCONTROL;
import javax.swing.JOptionPane;
import model.bean.ConfigBEAN;
import model.bean.UserBEAN;
import util.ConfigFileFactory;
import util.Encriptar;
import util.LoginMiddleware;

/**
 *
 * @author Usuario
 */
public class UserCreatorScreen extends javax.swing.JFrame {

    private boolean[] chbs = {false, false, true};

    public UserCreatorScreen() {
        initComponents();
        ConfigBEAN cb = new ConfigFileFactory().readFile();
        boolean opcs[] = cb.getOptions();
        chbSaveLogin.setSelected(opcs[1]);
        chbAutoLogin.setSelected(opcs[2]);
        chbAutoLogin.setEnabled(opcs[2]);
        chbs[0] = opcs[2];
        chbs[1] = opcs[1];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfNick = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfPass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        btnCarregar = new javax.swing.JButton();
        chbAutoLogin = new javax.swing.JCheckBox();
        chbSaveLogin = new javax.swing.JCheckBox();
        chbLoadSystem = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        tfConfPass = new javax.swing.JPasswordField();
        tfRole = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Criação De Usuario Administrador");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        tfNick.setBackground(new java.awt.Color(51, 51, 51));
        tfNick.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        tfNick.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nickname");

        tfEmail.setBackground(new java.awt.Color(51, 51, 51));
        tfEmail.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        tfEmail.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome Completo");

        tfName.setBackground(new java.awt.Color(51, 51, 51));
        tfName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        tfName.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Senha");

        tfPass.setBackground(new java.awt.Color(51, 51, 51));
        tfPass.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        tfPass.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirmar Senha");

        btnCarregar.setBackground(new java.awt.Color(0, 0, 0));
        btnCarregar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        btnCarregar.setForeground(new java.awt.Color(255, 255, 255));
        btnCarregar.setText("Salvar E Carregar");
        btnCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarActionPerformed(evt);
            }
        });

        chbAutoLogin.setBackground(new java.awt.Color(0, 0, 0));
        chbAutoLogin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        chbAutoLogin.setForeground(new java.awt.Color(255, 255, 255));
        chbAutoLogin.setText("Auto-Login");
        chbAutoLogin.setEnabled(false);
        chbAutoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbAutoLoginActionPerformed(evt);
            }
        });

        chbSaveLogin.setBackground(new java.awt.Color(0, 0, 0));
        chbSaveLogin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        chbSaveLogin.setForeground(new java.awt.Color(255, 255, 255));
        chbSaveLogin.setText("Salvar Login");
        chbSaveLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbSaveLoginActionPerformed(evt);
            }
        });

        chbLoadSystem.setBackground(new java.awt.Color(0, 0, 0));
        chbLoadSystem.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        chbLoadSystem.setForeground(new java.awt.Color(255, 255, 255));
        chbLoadSystem.setSelected(true);
        chbLoadSystem.setText("Carregar Sistema");
        chbLoadSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbLoadSystemActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cargo");

        tfConfPass.setBackground(new java.awt.Color(51, 51, 51));
        tfConfPass.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        tfConfPass.setForeground(new java.awt.Color(255, 255, 255));

        tfRole.setEditable(false);
        tfRole.setBackground(new java.awt.Color(51, 51, 51));
        tfRole.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        tfRole.setForeground(new java.awt.Color(255, 255, 255));
        tfRole.setText("admin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfRole, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(tfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(tfConfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(tfNick, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(chbLoadSystem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbSaveLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbAutoLogin)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfConfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(26, 26, 26)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbLoadSystem)
                    .addComponent(chbSaveLogin)
                    .addComponent(chbAutoLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCarregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chbLoadSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbLoadSystemActionPerformed
        boolean b = chbLoadSystem.isSelected();
        chbs[2] = b;
        if (b) {
            btnCarregar.setText("Salvar E Carregar");
        } else {
            btnCarregar.setText("Salvar E Fechar");
        }
    }//GEN-LAST:event_chbLoadSystemActionPerformed

    private void chbSaveLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbSaveLoginActionPerformed
        boolean b = chbSaveLogin.isSelected();
        chbs[0] = b;
        chbs[1] = b;
        chbAutoLogin.setSelected(b);
        chbAutoLogin.setEnabled(b);
    }//GEN-LAST:event_chbSaveLoginActionPerformed

    private void chbAutoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbAutoLoginActionPerformed
        chbs[0] = chbAutoLogin.isSelected();
    }//GEN-LAST:event_chbAutoLoginActionPerformed

    private void btnCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarActionPerformed
        UserBEAN ub = new UserBEAN();
        ub.setName(tfName.getText());
        ub.setEmail(tfEmail.getText());
        ub.setNick(tfNick.getText());
        ub.setRole("admin");
        String pass1 = Encriptar.toMD5(new String(tfPass.getPassword()));
        String pass2 = Encriptar.toMD5(new String(tfConfPass.getPassword()));
        if (pass1.equals(pass2)) {
            ub.setPassword(pass1);
            iniciar(ub);
        } else {
            JOptionPane.showMessageDialog(this, "Senhas São Diferentes", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCarregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserCreatorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserCreatorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserCreatorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserCreatorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserCreatorScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarregar;
    private javax.swing.JCheckBox chbAutoLogin;
    private javax.swing.JCheckBox chbLoadSystem;
    private javax.swing.JCheckBox chbSaveLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField tfConfPass;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfNick;
    private javax.swing.JPasswordField tfPass;
    private javax.swing.JTextField tfRole;
    // End of variables declaration//GEN-END:variables

    private void iniciar(UserBEAN ub) {
        setVisible(false);
        ConfigBEAN cb = new ConfigFileFactory().readFile();
        boolean opcs[] = cb.getOptions();
        if (chbs[1]) {
            cb.setSavedUser(ub);
        }
        opcs[1] = chbs[1];
        opcs[2] = chbs[0];
        cb.setOptions(opcs);
        new UserCONTROL().add(ub);
        try {
            Thread.sleep(3000);
        } catch (Exception e) {
        }
        new ConfigFileFactory().writeFile(cb);
        System.out.println("[XLIV-INFO] Atualizando Arquivo De Configurações");
        new ConfigFileFactory().writeFile(cb);
        System.out.println("[XLIV-INFO] Iniciando Login Middleware");
        new LoginMiddleware().login();
        dispose();
    }
}
